services:
  web:
    build:
      context: .
      target: production
    ports:
      - "8089:80"
    depends_on:
      - app
    volumes:
      - ./dist:/usr/share/nginx/html

  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    build:
      context: .
      target: builder
    command: npm run build

